### ISSUE TITLE
General task view improvements

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/Robust#1]
**Format:** We have converted the old XML-based task views file now to the new Markdown-based format. Please check the resulting .md file whether everything is in order or some corrections/improvements are needed. See the [corresponding documentation](https://github.com/cran-task-views/ctv/blob/main/Documentation.md) for more details.

**Update:** This would also be a good time to check the entire task whether it is up to date and correct. A write-up of the general goals and content guidelines is now summarized in the workflow for [proposing new task views](https://github.com/cran-task-views/ctv/blob/main/Proposal.md) (which was not yet available when you authored your task view). Improving your task view to conform more closely with these goals and guidelines, if necessary, would be highly appreciated.

**Co-maintainers:** In particular, we strongly encourage that all task views not only have a principal maintainer but also 1-5 co-maintainers in order to get more inspirations for extensions/improvements and share the maintenance workload. So please try to extend the list of co-maintainers, ideally also including female contributors and generally involving persons with diverse backgrounds.

**Comment by zeileis** [comment]
Martin @mmaechler, could you please have a look at the format of the task view and whether everything is in order when converting with `ctv::ctv2html("Robust.md", cran = TRUE)` using a recent version of `ctv` from R-Forge? Then we could turn the project "Public" and include it in the new CRAN workflow.

An update, if necessary, would also be nice but is not as urgent. Similarly, bringing co-maintainers on board could help keeping the task view active but this would also be possible at a later point.

**Comment by zeileis** [comment]
I have now made various small improvements so that the task view can be included in the new CRAN workflow. Hence I have also turned it "Public" here on GitHub and included it on the main ctv page.

It would be great if you could have another look at the view in the next weeks/months, check for updates and new packages on CRAN, and bring on board some co-maintainers that could help keeping the task view active and up-to-date.

**Comment by mmaechler** [comment]
I've done that with 84cac221c69168b2de2144540eaf7fa1c61f6cb4

**Comment by zeileis** [comment]
Thanks, Martin, very much appreciated!
